import { assets } from "./assets/assets";
export const data = {
  slider: [
    {
      term: "SUMMER 2020",
      title: "NEW COLLECTION",
      description:
        "We know how large objects will act, but things on a small scale.",
      button: "SHOP NOW",
      image: assets.sliders[0],
    },
    {
      term: "FALL 2020",
      title: "NEW COLLECTION",
      description:
        "We know how large objects will act, but things on a small scale.",
      button: "SHOP NOW",
      image: assets.sliders[0],
    },
  ],
  sliderBottom: [
    {
      term: "SUMMER 2020",
      title: "Vita Classic Product",
      description:
        "We know how large objects will act, We know how are objects will act, We know",
      price: "$16.48",
      button: "ADD TO CART",
      image: assets.sliders[1],
    },
    {
      term: "FALL 2020",
      title: "Vita Classic Product",
      description:
        "We know how large objects will act, We know how are objects will act, We know",
      price: "$16.48",
      button: "ADD TO CART",
      image: assets.sliders[1],
    },
  ],
  editorsPick: {
    heading: "EDITOR'S PICK",
    paragraph: "Problems trying to resolve the conflict bewtween",
    card: [
      { name: "MEN", image: assets.editorsPick[0] },
      { name: "WOMEN", image: assets.editorsPick[1] },
      { name: "ACCESSORIES", image: assets.editorsPick[2] },
      { name: "KIDS", image: assets.editorsPick[3] },
    ],
  },
  bestsellerProducts: {
    title: "Featured Products",
    heading: "BESTSELLER PRODUCTS",
    paragraph: "Problems trying to resolve the conflict between",
    card: [
      {
        name: "Graphic Design",
        description: "English Department",
        price: "$16.48",
        discounted: "$6.48",
        colors: [
          "w-4 h-4 rounded-full bg-[#23A6F0]",
          "w-4 h-4 rounded-full bg-[#23856D]",
          "w-4 h-4 rounded-full bg-[#E77C40]",
          "w-4 h-4 rounded-full bg-[#252B42]",
        ],
        image: assets.bestsellerProducts[0],
      },
      {
        name: "Graphic Design",
        description: "English Department",
        price: "$16.48",
        discounted: "$6.48",
        colors: [
          "w-4 h-4 rounded-full bg-[#23A6F0]",
          "w-4 h-4 rounded-full bg-[#23856D]",
          "w-4 h-4 rounded-full bg-[#E77C40]",
          "w-4 h-4 rounded-full bg-[#252B42]",
        ],
        image: assets.bestsellerProducts[1],
      },
      {
        name: "Graphic Design",
        description: "English Department",
        price: "$16.48",
        discounted: "$6.48",
        colors: [
          "w-4 h-4 rounded-full bg-[#23A6F0]",
          "w-4 h-4 rounded-full bg-[#23856D]",
          "w-4 h-4 rounded-full bg-[#E77C40]",
          "w-4 h-4 rounded-full bg-[#252B42]",
        ],
        image: assets.bestsellerProducts[2],
      },
      {
        name: "Graphic Design",
        description: "English Department",
        price: "$16.48",
        discounted: "$6.48",
        colors: [
          "w-4 h-4 rounded-full bg-[#23A6F0]",
          "w-4 h-4 rounded-full bg-[#23856D]",
          "w-4 h-4 rounded-full bg-[#E77C40]",
          "w-4 h-4 rounded-full bg-[#252B42]",
        ],
        image: assets.bestsellerProducts[3],
      },
      {
        name: "Graphic Design",
        description: "English Department",
        price: "$16.48",
        discounted: "$6.48",
        colors: [
          "w-4 h-4 rounded-full bg-[#23A6F0]",
          "w-4 h-4 rounded-full bg-[#23856D]",
          "w-4 h-4 rounded-full bg-[#E77C40]",
          "w-4 h-4 rounded-full bg-[#252B42]",
        ],
        image: assets.bestsellerProducts[4],
      },
      {
        name: "Graphic Design",
        description: "English Department",
        price: "$16.48",
        discounted: "$6.48",
        colors: [
          "w-4 h-4 rounded-full bg-[#23A6F0]",
          "w-4 h-4 rounded-full bg-[#23856D]",
          "w-4 h-4 rounded-full bg-[#E77C40]",
          "w-4 h-4 rounded-full bg-[#252B42]",
        ],
        image: assets.bestsellerProducts[5],
      },
      {
        name: "Graphic Design",
        description: "English Department",
        price: "$16.48",
        discounted: "$6.48",
        colors: [
          "w-4 h-4 rounded-full bg-[#23A6F0]",
          "w-4 h-4 rounded-full bg-[#23856D]",
          "w-4 h-4 rounded-full bg-[#E77C40]",
          "w-4 h-4 rounded-full bg-[#252B42]",
        ],
        image: assets.bestsellerProducts[6],
      },
      {
        name: "Graphic Design",
        description: "English Department",
        price: "$16.48",
        discounted: "$6.48",
        colors: [
          "w-4 h-4 rounded-full bg-[#23A6F0]",
          "w-4 h-4 rounded-full bg-[#23856D]",
          "w-4 h-4 rounded-full bg-[#E77C40]",
          "w-4 h-4 rounded-full bg-[#252B42]",
        ],
        image: assets.bestsellerProducts[7],
      },
    ],
  },
  neuralUniverse: {
    term: "SUMMER 2020",
    title: "Part of the Neural Universe",
    description:
      "We know how large objects will act, but things on a small scale.",
    button1: "BUY NOW",
    button2: "READ MORE",
    image: assets.neuralUniverse,
  },
  featuredPosts: {
    title: "Practice Advice",
    heading: "FEATURED POSTS",
    paragraph:
      "Problems trying to resolve the conflict between the two major realms of Classical physics: Newtonian mechanics ",
    card: [
      {
        links: ["Google", "Trending", "New"],
        name: "Loudest à la Madison #1 (L'integral)",
        description:
          "We focus on ergonomics and meeting you where you work. It's only a keystroke away.",
        date: "22 April 2021",
        comments: "10 comments",
        learnMore: "Learn More",
        image: assets.featuredPosts[0],
        label: "NEW",
      },
      {
        links: ["Google", "Trending", "New"],
        name: "Loudest à la Madison #1 (L'integral)",
        description:
          "We focus on ergonomics and meeting you where you work. It's only a keystroke away.",
        date: "22 April 2021",
        comments: "10 comments",
        learnMore: "Learn More",
        image: assets.featuredPosts[1],
        label: "NEW",
      },
      {
        links: ["Google", "Trending", "New"],
        name: "Loudest à la Madison #1 (L'integral)",
        description:
          "We focus on ergonomics and meeting you where you work. It's only a keystroke away.",
        date: "22 April 2021",
        comments: "10 comments",
        learnMore: "Learn More",
        image: assets.featuredPosts[2],
        label: "NEW",
      },
    ],
  },
  shop: {
    categoryCards: [
      { title: "CLOTHS", amount: 5, image: assets.categoryCards[0] },
      { title: "CLOTHS", amount: 5, image: assets.categoryCards[1] },
      { title: "CLOTHS", amount: 5, image: assets.categoryCards[2] },
      { title: "CLOTHS", amount: 5, image: assets.categoryCards[3] },
      { title: "CLOTHS", amount: 5, image: assets.categoryCards[4] },
    ],
    productCards: [
      {
        name: "Graphic Design",
        description: "English Department",
        price: "$16.48",
        discounted: "$6.48",
        colors: [
          "w-4 h-4 rounded-full bg-[#23A6F0]",
          "w-4 h-4 rounded-full bg-[#23856D]",
          "w-4 h-4 rounded-full bg-[#E77C40]",
          "w-4 h-4 rounded-full bg-[#252B42]",
        ],
        image: assets.productCards[0],
      },
      {
        name: "Graphic Design",
        description: "English Department",
        price: "$16.48",
        discounted: "$6.48",
        colors: [
          "w-4 h-4 rounded-full bg-[#23A6F0]",
          "w-4 h-4 rounded-full bg-[#23856D]",
          "w-4 h-4 rounded-full bg-[#E77C40]",
          "w-4 h-4 rounded-full bg-[#252B42]",
        ],
        image: assets.productCards[1],
      },
      {
        name: "Graphic Design",
        description: "English Department",
        price: "$16.48",
        discounted: "$6.48",
        colors: [
          "w-4 h-4 rounded-full bg-[#23A6F0]",
          "w-4 h-4 rounded-full bg-[#23856D]",
          "w-4 h-4 rounded-full bg-[#E77C40]",
          "w-4 h-4 rounded-full bg-[#252B42]",
        ],
        image: assets.productCards[2],
      },
      {
        name: "Graphic Design",
        description: "English Department",
        price: "$16.48",
        discounted: "$6.48",
        colors: [
          "w-4 h-4 rounded-full bg-[#23A6F0]",
          "w-4 h-4 rounded-full bg-[#23856D]",
          "w-4 h-4 rounded-full bg-[#E77C40]",
          "w-4 h-4 rounded-full bg-[#252B42]",
        ],
        image: assets.productCards[3],
      },
      {
        name: "Graphic Design",
        description: "English Department",
        price: "$16.48",
        discounted: "$6.48",
        colors: [
          "w-4 h-4 rounded-full bg-[#23A6F0]",
          "w-4 h-4 rounded-full bg-[#23856D]",
          "w-4 h-4 rounded-full bg-[#E77C40]",
          "w-4 h-4 rounded-full bg-[#252B42]",
        ],
        image: assets.productCards[4],
      },
      {
        name: "Graphic Design",
        description: "English Department",
        price: "$16.48",
        discounted: "$6.48",
        colors: [
          "w-4 h-4 rounded-full bg-[#23A6F0]",
          "w-4 h-4 rounded-full bg-[#23856D]",
          "w-4 h-4 rounded-full bg-[#E77C40]",
          "w-4 h-4 rounded-full bg-[#252B42]",
        ],
        image: assets.productCards[5],
      },
      {
        name: "Graphic Design",
        description: "English Department",
        price: "$16.48",
        discounted: "$6.48",
        colors: [
          "w-4 h-4 rounded-full bg-[#23A6F0]",
          "w-4 h-4 rounded-full bg-[#23856D]",
          "w-4 h-4 rounded-full bg-[#E77C40]",
          "w-4 h-4 rounded-full bg-[#252B42]",
        ],
        image: assets.productCards[6],
      },
      {
        name: "Graphic Design",
        description: "English Department",
        price: "$16.48",
        discounted: "$6.48",
        colors: [
          "w-4 h-4 rounded-full bg-[#23A6F0]",
          "w-4 h-4 rounded-full bg-[#23856D]",
          "w-4 h-4 rounded-full bg-[#E77C40]",
          "w-4 h-4 rounded-full bg-[#252B42]",
        ],
        image: assets.productCards[7],
      },
      {
        name: "Graphic Design",
        description: "English Department",
        price: "$16.48",
        discounted: "$6.48",
        colors: [
          "w-4 h-4 rounded-full bg-[#23A6F0]",
          "w-4 h-4 rounded-full bg-[#23856D]",
          "w-4 h-4 rounded-full bg-[#E77C40]",
          "w-4 h-4 rounded-full bg-[#252B42]",
        ],
        image: assets.productCards[8],
      },
      {
        name: "Graphic Design",
        description: "English Department",
        price: "$16.48",
        discounted: "$6.48",
        colors: [
          "w-4 h-4 rounded-full bg-[#23A6F0]",
          "w-4 h-4 rounded-full bg-[#23856D]",
          "w-4 h-4 rounded-full bg-[#E77C40]",
          "w-4 h-4 rounded-full bg-[#252B42]",
        ],
        image: assets.productCards[9],
      },
      {
        name: "Graphic Design",
        description: "English Department",
        price: "$16.48",
        discounted: "$6.48",
        colors: [
          "w-4 h-4 rounded-full bg-[#23A6F0]",
          "w-4 h-4 rounded-full bg-[#23856D]",
          "w-4 h-4 rounded-full bg-[#E77C40]",
          "w-4 h-4 rounded-full bg-[#252B42]",
        ],
        image: assets.productCards[10],
      },
      {
        name: "Graphic Design",
        description: "English Department",
        price: "$16.48",
        discounted: "$6.48",
        colors: [
          "w-4 h-4 rounded-full bg-[#23A6F0]",
          "w-4 h-4 rounded-full bg-[#23856D]",
          "w-4 h-4 rounded-full bg-[#E77C40]",
          "w-4 h-4 rounded-full bg-[#252B42]",
        ],
        image: assets.productCards[11],
      },
    ],
  },
  brandsInShop: [
    assets.brandsInShop[0],
    assets.brandsInShop[1],
    assets.brandsInShop[2],
    assets.brandsInShop[3],
    assets.brandsInShop[4],
    assets.brandsInShop[5],
  ],
  productSlider: [assets.productSlider[0], assets.productSlider[1]],
  productDetail: {
    image: assets.product[0],
  },
  productBestseller: [
    assets.productBestseller[0],
    assets.productBestseller[1],
    assets.productBestseller[2],
    assets.productBestseller[3],
    assets.productBestseller[4],
    assets.productBestseller[5],
    assets.productBestseller[6],
    assets.productBestseller[7],
  ],
  about: [
    assets.about.top[0],
    assets.about.top[1],
    assets.about.top[2],
    assets.about.top[3],
    assets.about.top[4],
    assets.about.top[5],
  ],
  aboutVideo: assets.about.video,
  aboutTeam: [assets.about.team[0], assets.about.team[1], assets.about.team[2]],
};
